### ISSUE TITLE
Calculator RAM clears or crashes after garbage collecting

### ISSUE THREAD

**Issue by DJOmnimaga** [jacobly0/asmhook#3]
Once ASMHOOK is installed on my TI-84 Plus CE (pre-A hardware), if I run a garbage collect, then after defragmenting is done the calculator reboots with a RAM clear. EDIT Tested on boot code 5.0.0.0089 and OS 5.6.0.0020

**Comment by jacobly0** [comment]
Fixed in release v1.0.1.
