### ISSUE TITLE
Is there a way to remove asmhook without clearing RAM? 

### ISSUE THREAD

**Issue by JLP04** [jacobly0/asmhook#4]
I was wondering if it was possible to remove asmhook without clearing my RAM? For example, if I wanted to temporarily install it so I could use tilp to sync the calculator time with the system time on my computer and then wanted to uninstall it afterwards without clearing the RAM which would reset the clock on the calculator.

**Comment by jacobly0** [comment]
You do not need ASMHOOK to sync the calculator time with your PC using TILP.

**Comment by JLP04** [comment]
Whenever I try doing it, it errors out since tilp uses assembly and the calculator won't run assembly.

**Comment by adriweb** [comment]
It doesn't use ASM to set the clock, that's one of the features of TI's protocol. If it errors, it would be for another reason.

**Comment by JLP04** [comment]
I realized I was mixing it up with the ROM dump. Thanks for the help though.
