### ISSUE TITLE
Using BackgroundOn in a For( loop  causes programs to restart

### ISSUE THREAD

**Issue by NinjaWeedle** [jacobly0/asmhook#5]
Whenever ASMHOOK is active, Using the BackgroundOn within a For( loop in a TI-BASIC program causes the program to restart from the beginning.

The step and values of the For( loop don't matter, the only thing that matters is that BackgroundOn was used within the loop.

Easily demonstrable by using this:

Disp "THIS TEXT SHOULD NOT APPEAR MORE THAN ONCE
For([Any variable],[any value],[any value]
BackgroundOn
End

**Comment by jyoung-gm** [comment]
Can you give me your exact boot and os (base) versions.  These can be found in the self test menu, which you can get to by pressing `mode` `alpha` `ln`.  You can press `2nd` `mode` to quit from this without erasing anything.  Also your hardware revision which can be found on the back of the calculator, for example `I-0417L`.

**Comment by NinjaWeedle** [comment]
This bug has occurred for me on os 5.7 and 5.8.0.022 (haven't tested earlier versions, I assume it occurs there too), with BOOT Code 5.6.1.0006 on a TI-84 Plus CE Python with serial C174000A2.

**Comment by adriweb** [comment]
( `C174000A2` is equivalent to late April 2021, for a Python 84+CE, that would be around rev R or S )

**Comment by jacobly0** [comment]
Closed by [v1.0.2](https://github.com/jacobly0/asmhook/releases/tag/v1.0.2).
